spring.application.name=to-do-list

spring.datasource.url=jdbc:postgresql://localhost:5433/taskdb
spring.datasource.username=sisonke
spring.datasource.password=Boyilani10*
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Enable execution of data.sql on startup
spring.sql.init.mode=always
