apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: to-do-list
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskdb
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
